module "rabbitmq_service" {
  source = "./modules/rabbitmq"
  RABBITMQ_ERLANG_COOKIE = var.RABBITMQ_ERLANG_COOKIE
  RABBITMQ_DEFAULT_USER = var.RABBITMQ_DEFAULT_USER
  RABBITMQ_DEFAULT_PASS = var.RABBITMQ_DEFAULT_PASS
  RABBITMQ_DEFAULT_VHOST = var.RABBITMQ_DEFAULT_VHOST
}