version: '3'

services:
  ansible:
    build: ./ansible
    container_name: ansible
    command: [ "tail", "-f", "/dev/null" ]
    hostname: ansible
    volumes:
      - ./ansible:/root/ansible

  terraform:
    build: ./terraform
    container_name: terraform
    command: [ "tail", "-f", "/dev/null" ]
    hostname: terraform
    volumes:
      - ./terraform:/root/terraform
