---
- hosts: all
  become: yes

  roles:
    - setup_docker
    - setup_terraform

  tasks:
    - name: Checkout Users Service develop branch
      git:
        repo: 'https://github.com/fireheet/users.git'
        dest: "{{ lookup('env','USERS_SVC_PATH') }}"
        version: develop
      ignore_errors: true
