---
- hosts: all
  remote_user: infra
  become: yes

  roles:
    - setup_docker

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    
    - name: Start nginx
      service:
        name: nginx
        state: started